### PR TITLE
Add automated testing (via catkin_virtualenv)

### PR DESCRIPTION
**Pull request by ggaessler**
Since the ROS buildfarm currently doesn't handle PIP test dependencies correctly (https://github.com/ros-infrastructure/ros_buildfarm/issues/895) and there are currently no resources to fix it (neither on OSRF nor on Bosch side) I've changed the PR (https://github.com/ros-drivers/nmea_navsat_driver/pull/130) to use catkin_virtualenv for the PIP testing dependencies. I preferred the other way, but this way it is still ensured that no PIP dependencies end up in the package. 

--- 

Porting the first feature from the boschresearch fork back to upstream: testing 

Automatically test the code on every push or PR by playing back data to the driver and test whether the expected amount of messages is outputted by the driver and the messages contain the expected data. 

The tester can cover more functionality that the current version of the nmea_navsat_driver supports, for these features new PRs will be created. The full usage can be observed in the boschresearch fork. 

Warning: Github Actions are not very reliable in combination with ROS right now. The tests sometimes randomly get stale and run into the timeout. In these cases the tests should be re-run manually. Since the test is expected to take less than 5 minutes I've set to timeout to 10 minutes, otherwise it would take the full 6 hours, which is the Github Actions default setting.

### CODE REVIEW

**Comment by ggaessler** [comment]
Are there any updates?

**Comment by evenator** [comment]
Hey, sorry I took so long to review this. I think it looks good to merge. Thanks for the contribution!

**Comment by ggaessler** [comment]
Unfortunately the automated testing is not working right now since ros-tooling is broken since some days and therefore can't setup a testing environment: https://github.com/ros-tooling/setup-ros/issues/460
The proposed workaround unfortunately can't be easily integrated into the ci.yaml. Hopefully the bug will be fixed soon.

**Comment by ggaessler** [comment]
@evenator please re-run the action via the three dots at the top-right of https://github.com/ros-drivers/nmea_navsat_driver/actions/runs/1646715390. `ros-tooling` should be fixed in the meantime. Thanks!

**Comment by evenator** [comment]
@ggaessler Apparently one can only re-run a workflow for 30 days, so I can't re-run that.

**Comment by ggaessler** [comment]
> @ggaessler Apparently one can only re-run a workflow for 30 days, so I can't re-run that.

Ok. Thanks for trying. Create a new PR to "re-run" it: https://github.com/ros-drivers/nmea_navsat_driver/pull/144
Unfurtunately the Github runner was way slower than it used to be and just idled the first 9 minutes, causing the timeout to trigger after 1 more minute. This is fixed here:
https://github.com/ros-drivers/nmea_navsat_driver/pull/145

**Pull request merged**
